# Generated by Django 4.1.4 on 2022-12-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('crop_name', models.CharField(max_length=100)),
                ('seed_type', models.CharField(max_length=100)),
                ('quality', models.CharField(max_length=25)),
                ('quantity', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
