# Generated by Django 4.1.4 on 2022-12-15 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Slot',
            new_name='Table',
        ),
    ]
